Добавляю инструкцию по использованию
publickyrgyzstan/projects pull request #14
Opened 2020-10-19 07:23 UTC by dastanko

2020-10-19 10:08 UTC, sayakbayev commented on README.md
> +* Заполнить форму для участия. Мы с вами свяжемся и дадим доступ.
Думаю лучше написать что-то подобное в файле с текстом законопроекта в майн ветке. Во-первых майн ветке файл пустой и это может смущать людей, а во-вторых, зачем два фала в репозитории, это тоже может кого-то запутать.

2020-10-20 16:35 UTC, max91solomon approved these changes

2020-10-20 17:29 UTC, sayakbaev requested changes
не надо, в ветку майн же запостили уже

2020-10-24 05:47 UTC, sayakbayev commented
@dastanko я только сейчас понял для чего нужен этот файл :) На странице репозитория он сразу текст показывает, а другие файлы не показывают. Напишу чуть позже текст в него.

2020-10-25 10:33 UTC, sayakbaev approved these changes

2020-10-25 10:34 UTC, merged